metadataFolder/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Annual_Revenue__c</fullName>
        <label>Annual Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <description>Set to the company of a lead</description>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NumberOfEmployees__c</fullName>
        <label>No. of Employees</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Concept Paper</fullName>
                    <default>true</default>
                    <label>Concept Paper</label>
                </value>
                <value>
                    <fullName>Full Application</fullName>
                </value>
                <value>
                    <fullName>Selection</fullName>
                </value>
                <value>
                    <fullName>Negotiation</fullName>
                </value>
                <value>
                    <fullName>Project Performance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
</CustomObject>

metadataFolder/objects/User.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/User/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ApplicationControllerTest.cls
@isTest
public class ApplicationControllerTest {
    @testSetup
    static void setupTestData() {
        // Create a test Application
        Application__c testApplication = new Application__c(
            Name = 'Son Goku',
            Stage__c = 'Concept Paper',
            Phone__c = '1111111111',
            Company__c = 'Denki Houdai',
            Description__c = 'We develop solar powered hot dogs',
            Annual_Revenue__c = 1000000,
            Email__c = 'mmatos@skillstorm.com',
            NumberOfEmployees__c = 5000
        );
        insert testApplication;

        // Create a test User
        User testUser = new User(
            Username = 'Toph@beifong.com',
            Email = 'Toph@beifong.com',
            LastName = 'Beifong',
            Alias = 'tBei',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            Application__c = testApplication.Id
        );
        insert testUser;
    }

    @isTest
    static void testPositive() {

        User testUser = [SELECT Id FROM User WHERE Username = 'Toph@beifong.com' LIMIT 1];


        System.runAs(testUser) {
            Application__c result = ApplicationController.getApplicationInfo();

            System.assertNotEquals(null, result);
            System.assertEquals('Son Goku', result.Name);
            System.assertEquals('Concept Paper', result.Stage__c);
            System.assertEquals('1111111111', result.Phone__c);
            System.assertEquals('Denki Houdai', result.Company__c);
            System.assertEquals('We develop solar powered hot dogs', result.Description__c);
            System.assertEquals(1000000, result.Annual_Revenue__c);
            System.assertEquals('mmatos@skillstorm.com', result.Email__c);
            System.assertEquals(5000, result.NumberOfEmployees__c);
        }
    }

    @isTest
    static void testNegative() {


        User testUser2 = new User(
            Username = 'Toph2@beifong.com',
            Email = 'Toph2@beifong.com',
            LastName = 'Beifong',
            Alias = 'tBei',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert testUser2;

        System.runAs(testUser2) {
            Application__c result = ApplicationController.getApplicationInfo();

            System.assertEquals(null, result);
        }
    }
}