metadataFolder/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Company__c</fullName>
        <description>Set to the company of a lead</description>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Concept Paper</fullName>
                    <default>true</default>
                    <label>Concept Paper</label>
                </value>
                <value>
                    <fullName>Full Application</fullName>
                </value>
                <value>
                    <fullName>Selection</fullName>
                </value>
                <value>
                    <fullName>Negotiation</fullName>
                </value>
                <value>
                    <fullName>Project Performance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
</CustomObject>

metadataFolder/objects/User.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/User/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

metadataFolder/classes/ApplicationController.cls
public with sharing class ApplicationController {
    public ApplicationController() {

    }

    @AuraEnabled(cacheable=true)
    public static Application__c getApplicationInfo() {
        Id userId = UserInfo.getUserId();

        User loggedInUser = [
            SELECT Application__c 
            FROM User 
            WHERE Id = :userId 
            LIMIT 1
        ];


        if (loggedInUser.Application__c != null) {
            Application__c userApp = [
                SELECT Id, Name, Stage__c, Phone__c, Company__c 
                FROM Application__c 
                WHERE Id = :loggedInUser.Application__c
                LIMIT 1
            ];
            return userApp;
        } else {
            System.debug('No associated application found for the user.');
            return null;
        }
    }
}